sudo: required
services:
  - docker

before_install:
  - docker build -t ori/docker-basic -f Dockerfile .

script:
    - docker run -e CI=true ori/docker-basic npm run test 

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-basic"
    env: "DockerBasic-env"
    bucket_name: "elasticbeanstalk-us-east-1-201546747467"
    bucket_path: "docker-basic"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure:  $AWS_SECRET_KEY